# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            qpler
tagline:          ''
description:      ''
url:              qpler.github.io
baseurl:          /

author:
  name:           'Francisco Garrido Matta'
  url:            https://twitter.com/flgarrid

paginate:         5

# Custom vars
version:          1.0
