# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            qpler - Technology and Research
tagline:          ''
description:      ''
url:              http://www.qpler.com
blog_url:         http://tob.qpler.com

author:
  name:           'qpler'
  url:            http://www.qpler.com

paginate:         5

# Custom vars
version:          1.0
